import { Maid, Booking, Customer, Notification, AdminStats, AppSettings, ServiceCategory } from './types';

// ============================================================
// SERVICE CATEGORIES
// ============================================================

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: 'cleaning', name: 'Cleaning', emoji: '🧹', active: true },
  { id: 'cooking', name: 'Cooking', emoji: '🍳', active: true },
  { id: 'babysitting', name: 'Babysitting', emoji: '👶', active: true },
  { id: 'elder_care', name: 'Elder Care', emoji: '🧓', active: true },
  { id: 'house_help', name: 'House Help', emoji: '🏠', active: true },
  { id: 'laundry', name: 'Laundry', emoji: '👕', active: true },
  { id: 'full_day', name: 'Full Day', emoji: '🌞', active: true },
  { id: 'part_time', name: 'Part Time', emoji: '⏰', active: true },
];

// ============================================================
// SUPPORTED AREAS
// ============================================================

export const SUPPORTED_CITIES = ['Bhilai', 'Durg', 'Raipur', 'Bilaspur', 'Rajnandgaon'];

export const SUPPORTED_AREAS: Record<string, string[]> = {
  Bhilai: [
    'Sector 1', 'Sector 2', 'Sector 4', 'Sector 6', 'Sector 7', 'Sector 9',
    'Nehru Nagar', 'Supela', 'Smriti Nagar', 'Civic Centre', 'Junwani',
    'Risali', 'Bhilai-3', 'Bhilai Nagar', 'Durg Road',
  ],
  Durg: [
    'Nehru Chowk', 'Shankar Nagar', 'Padmanabhpur', 'Transport Nagar',
    'Ram Nagar', 'Ganjpara', 'Utai', 'Boria',
  ],
  Raipur: [
    'Pandri', 'Telibandha', 'Tatibandh', 'Shankar Nagar', 'Amanaka',
    'Tikrapara', 'Devendra Nagar', 'Pachpedi Naka', 'Vidhan Sabha',
  ],
  Bilaspur: ['Sadar Bazar', 'Torwa', 'Talapara', 'Gole Bazar'],
  Rajnandgaon: ['Main Road', 'Chhindwara Road', 'Khairagarh'],
};

// ============================================================
// MOCK MAIDS
// ============================================================

export const MOCK_MAIDS: Maid[] = [
  {
    id: 'maid-1',
    userId: 'user-m1',
    name: 'Sunita Verma',
    phone: '9876543210',
    email: 'sunita.verma@gmail.com',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=47',
    verificationStatus: 'verified',
    selfieStatus: 'verified',
    approvalStatus: 'approved',
    aadhaarMasked: 'XXXX-XXXX-XXXX-4521',
    location: 'Bhilai',
    city: 'Bhilai',
    area: 'Nehru Nagar',
    address: 'Near Durga Mandir',
    pincode: '490020',
    serviceAreas: ['Nehru Nagar', 'Sector 6', 'Sector 7', 'Civic Centre'],
    workRadius: 5,
    qualification: 'Matriculation (10th)',
    experience: 8,
    services: ['Cleaning', 'Cooking', 'House Help'],
    languages: ['Hindi', 'Chhattisgarhi'],
    bio: 'Experienced and trustworthy house helper. Specializes in deep cleaning and cooking. Available for part-time and full-day work.',
    hourlyPrice: 150,
    dailyPrice: 800,
    monthlyPrice: 18000,
    availability: 'available',
    rating: 4.8,
    totalRatings: 124,
    totalBookings: 156,
    completedBookings: 148,
    profileViews: 890,
    isActive: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-08-20T08:00:00Z',
  },
  {
    id: 'maid-2',
    userId: 'user-m2',
    name: 'Rekha Patel',
    phone: '9765432109',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=49',
    verificationStatus: 'verified',
    selfieStatus: 'verified',
    approvalStatus: 'approved',
    aadhaarMasked: 'XXXX-XXXX-XXXX-7832',
    location: 'Bhilai',
    city: 'Bhilai',
    area: 'Sector 4',
    serviceAreas: ['Sector 4', 'Sector 6', 'Smriti Nagar', 'Supela'],
    workRadius: 4,
    qualification: 'Higher Secondary (12th)',
    experience: 5,
    services: ['Babysitting', 'Elder Care', 'Cooking'],
    languages: ['Hindi', 'English'],
    bio: 'Gentle and caring personality. Excellent with children and elderly. Background in nursing support.',
    hourlyPrice: 180,
    dailyPrice: 950,
    monthlyPrice: 20000,
    availability: 'available',
    rating: 4.9,
    totalRatings: 87,
    totalBookings: 102,
    completedBookings: 99,
    profileViews: 645,
    isActive: true,
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-08-18T08:00:00Z',
  },
  {
    id: 'maid-3',
    userId: 'user-m3',
    name: 'Kavita Sahu',
    phone: '9654321098',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=46',
    verificationStatus: 'verified',
    selfieStatus: 'verified',
    approvalStatus: 'approved',
    aadhaarMasked: 'XXXX-XXXX-XXXX-3344',
    location: 'Bhilai',
    city: 'Bhilai',
    area: 'Smriti Nagar',
    serviceAreas: ['Smriti Nagar', 'Junwani', 'Civic Centre', 'Sector 9'],
    workRadius: 6,
    qualification: 'Matriculation (10th)',
    experience: 12,
    services: ['Cleaning', 'Laundry', 'House Help', 'Cooking'],
    languages: ['Hindi', 'Chhattisgarhi'],
    bio: 'Highly experienced in all types of housework. Available for monthly contracts at competitive rates.',
    hourlyPrice: 130,
    dailyPrice: 700,
    monthlyPrice: 15000,
    availability: 'available',
    rating: 4.6,
    totalRatings: 210,
    totalBookings: 280,
    completedBookings: 268,
    profileViews: 1240,
    isActive: true,
    createdAt: '2023-06-01T10:00:00Z',
    updatedAt: '2024-08-22T08:00:00Z',
  },
  {
    id: 'maid-4',
    userId: 'user-m4',
    name: 'Priya Tiwari',
    phone: '9543210987',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=44',
    verificationStatus: 'verified',
    selfieStatus: 'verified',
    approvalStatus: 'approved',
    aadhaarMasked: 'XXXX-XXXX-XXXX-5678',
    location: 'Durg',
    city: 'Durg',
    area: 'Nehru Chowk',
    serviceAreas: ['Nehru Chowk', 'Shankar Nagar', 'Padmanabhpur'],
    workRadius: 5,
    qualification: 'Graduate (BA)',
    experience: 3,
    services: ['Babysitting', 'Cooking', 'Cleaning'],
    languages: ['Hindi', 'English', 'Chhattisgarhi'],
    bio: 'Well-educated and professional. Specializes in childcare and tutoring support for kids.',
    hourlyPrice: 200,
    dailyPrice: 1100,
    monthlyPrice: 22000,
    availability: 'available',
    rating: 4.7,
    totalRatings: 56,
    totalBookings: 68,
    completedBookings: 65,
    profileViews: 430,
    isActive: true,
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-08-25T08:00:00Z',
  },
  {
    id: 'maid-5',
    userId: 'user-m5',
    name: 'Meena Yadav',
    phone: '9432109876',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=48',
    verificationStatus: 'verified',
    selfieStatus: 'verified',
    approvalStatus: 'approved',
    aadhaarMasked: 'XXXX-XXXX-XXXX-9012',
    location: 'Bhilai',
    city: 'Bhilai',
    area: 'Supela',
    serviceAreas: ['Supela', 'Bhilai-3', 'Risali', 'Nehru Nagar'],
    workRadius: 7,
    qualification: 'Middle School (8th)',
    experience: 15,
    services: ['House Help', 'Cleaning', 'Laundry', 'Cooking'],
    languages: ['Hindi', 'Chhattisgarhi'],
    bio: 'Very experienced and reliable. 15 years of working in homes. Excellent references available.',
    hourlyPrice: 120,
    dailyPrice: 650,
    monthlyPrice: 13000,
    availability: 'busy',
    rating: 4.5,
    totalRatings: 342,
    totalBookings: 420,
    completedBookings: 405,
    profileViews: 2100,
    isActive: true,
    createdAt: '2022-01-01T10:00:00Z',
    updatedAt: '2024-08-28T08:00:00Z',
  },
  {
    id: 'maid-6',
    userId: 'user-m6',
    name: 'Anita Sharma',
    phone: '9321098765',
    gender: 'female',
    profilePhoto: 'https://i.pravatar.cc/300?img=45',
    verificationStatus: 'pending',
    selfieStatus: 'verification_pending',
    approvalStatus: 'under_review',
    location: 'Raipur',
    city: 'Raipur',
    area: 'Pandri',
    serviceAreas: ['Pandri', 'Telibandha'],
    workRadius: 4,
    qualification: 'Higher Secondary (12th)',
    experience: 6,
    services: ['Elder Care', 'Cooking', 'House Help'],
    languages: ['Hindi'],
    hourlyPrice: 160,
    dailyPrice: 900,
    availability: 'available',
    rating: undefined,
    isActive: false,
    createdAt: '2024-08-20T10:00:00Z',
    updatedAt: '2024-08-25T08:00:00Z',
  },
];

// ============================================================
// MOCK CUSTOMERS
// ============================================================

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    role: 'customer',
    name: 'Rahul Gupta',
    phone: '9876500001',
    email: 'rahul.gupta@gmail.com',
    photoUrl: 'https://i.pravatar.cc/300?img=11',
    location: 'Bhilai',
    area: 'Sector 7',
    address: 'House No. 42, Sector 7, Bhilai',
    preferredArea: 'Sector 7',
    status: 'active',
    totalBookings: 8,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'cust-2',
    role: 'customer',
    name: 'Priya Singh',
    phone: '9876500002',
    email: 'priya.singh@gmail.com',
    photoUrl: 'https://i.pravatar.cc/300?img=20',
    location: 'Bhilai',
    area: 'Smriti Nagar',
    status: 'active',
    totalBookings: 3,
    createdAt: '2024-03-15T10:00:00Z',
  },
];

// ============================================================
// MOCK BOOKINGS
// ============================================================

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    bookingNumber: 'MB-240801',
    customerId: 'cust-1',
    customerName: 'Rahul Gupta',
    maidId: 'maid-1',
    maidName: 'Sunita Verma',
    maidPhoto: 'https://i.pravatar.cc/300?img=47',
    serviceId: 'cleaning',
    serviceName: 'Cleaning',
    date: '2024-09-05',
    time: '09:00',
    duration: 4,
    pricingType: 'hourly',
    serviceAmount: 600,
    platformFee: 30,
    tax: 0,
    discount: 0,
    totalAmount: 630,
    paymentStatus: 'paid',
    paymentGateway: 'razorpay',
    transactionId: 'pay_TXN12345',
    bookingStatus: 'confirmed',
    customerAddress: 'House No. 42, Sector 7, Bhilai',
    customerArea: 'Sector 7',
    createdAt: '2024-08-30T10:00:00Z',
    updatedAt: '2024-08-30T10:30:00Z',
  },
  {
    id: 'bk-002',
    bookingNumber: 'MB-240802',
    customerId: 'cust-1',
    customerName: 'Rahul Gupta',
    maidId: 'maid-2',
    maidName: 'Rekha Patel',
    maidPhoto: 'https://i.pravatar.cc/300?img=49',
    serviceId: 'babysitting',
    serviceName: 'Babysitting',
    date: '2024-08-15',
    time: '10:00',
    duration: 8,
    pricingType: 'daily',
    serviceAmount: 950,
    platformFee: 48,
    tax: 0,
    discount: 0,
    totalAmount: 998,
    paymentStatus: 'paid',
    paymentGateway: 'phonepe',
    transactionId: 'PP_TXN54321',
    bookingStatus: 'completed',
    customerAddress: 'House No. 42, Sector 7, Bhilai',
    customerArea: 'Sector 7',
    createdAt: '2024-08-10T09:00:00Z',
    updatedAt: '2024-08-15T18:00:00Z',
  },
  {
    id: 'bk-003',
    bookingNumber: 'MB-240803',
    customerId: 'cust-1',
    customerName: 'Rahul Gupta',
    maidId: 'maid-3',
    maidName: 'Kavita Sahu',
    maidPhoto: 'https://i.pravatar.cc/300?img=46',
    serviceId: 'cleaning',
    serviceName: 'Cleaning',
    date: '2024-07-20',
    time: '08:00',
    duration: 3,
    pricingType: 'hourly',
    serviceAmount: 390,
    platformFee: 20,
    tax: 0,
    discount: 50,
    totalAmount: 360,
    paymentStatus: 'paid',
    paymentGateway: 'razorpay',
    transactionId: 'pay_TXN99887',
    bookingStatus: 'cancelled',
    customerAddress: 'House No. 42, Sector 7, Bhilai',
    customerArea: 'Sector 7',
    notes: 'Cancelled by customer',
    createdAt: '2024-07-18T10:00:00Z',
    updatedAt: '2024-07-19T09:00:00Z',
  },
];

// ============================================================
// MOCK MAID BOOKINGS
// ============================================================

export const MOCK_MAID_BOOKINGS: Booking[] = [
  {
    id: 'mbk-001',
    bookingNumber: 'MB-240901',
    customerId: 'cust-1',
    customerName: 'Rahul Gupta',
    maidId: 'maid-1',
    maidName: 'Sunita Verma',
    maidPhoto: 'https://i.pravatar.cc/300?img=47',
    serviceId: 'cleaning',
    serviceName: 'Cleaning',
    date: '2024-09-10',
    time: '09:00',
    duration: 4,
    pricingType: 'hourly',
    serviceAmount: 600,
    platformFee: 30,
    tax: 0,
    discount: 0,
    totalAmount: 630,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    customerAddress: 'House No. 42, Sector 7, Bhilai',
    customerArea: 'Sector 7',
    createdAt: '2024-09-05T10:00:00Z',
    updatedAt: '2024-09-05T10:30:00Z',
  },
  {
    id: 'mbk-002',
    bookingNumber: 'MB-240902',
    customerId: 'cust-2',
    customerName: 'Priya Singh',
    maidId: 'maid-1',
    maidName: 'Sunita Verma',
    maidPhoto: 'https://i.pravatar.cc/300?img=47',
    serviceId: 'cooking',
    serviceName: 'Cooking',
    date: '2024-09-12',
    time: '07:30',
    duration: 2,
    pricingType: 'hourly',
    serviceAmount: 300,
    platformFee: 15,
    tax: 0,
    discount: 0,
    totalAmount: 315,
    paymentStatus: 'pending',
    bookingStatus: 'awaiting_maid',
    customerAddress: 'B-12 Smriti Nagar, Bhilai',
    customerArea: 'Smriti Nagar',
    createdAt: '2024-09-06T08:00:00Z',
    updatedAt: '2024-09-06T08:00:00Z',
  },
];

// ============================================================
// MOCK NOTIFICATIONS
// ============================================================

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'cust-1',
    title: 'Booking Confirmed!',
    message: 'Your booking with Sunita Verma on Sep 5 is confirmed.',
    type: 'booking',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'cust-1',
    title: 'Payment Successful',
    message: '₹630 paid successfully for booking MB-240801.',
    type: 'payment',
    read: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'cust-1',
    title: 'Booking Completed',
    message: 'Your session with Rekha Patel has been completed. Please rate your experience.',
    type: 'booking',
    read: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'cust-1',
    title: 'Welcome to MaidEasy!',
    message: 'Find and book trusted maids in your area. Get started today!',
    type: 'system',
    read: true,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ============================================================
// MOCK ADMIN STATS
// ============================================================

export const MOCK_ADMIN_STATS: AdminStats = {
  customers: { total: 1248, newThisMonth: 87 },
  maids: { total: 94, pending: 6, approved: 82, rejected: 4, suspended: 2 },
  bookings: { total: 3420, pending: 28, confirmed: 45, completed: 3102, cancelled: 245 },
  revenue: { gross: 2840000, platform: 142000, thisMonth: 184500 },
};

// ============================================================
// APP SETTINGS
// ============================================================

export const DEFAULT_APP_SETTINGS: AppSettings = {
  general: {
    appName: 'MaidEasy',
    appDescription: 'Trusted maid and home service booking platform for India',
    supportEmail: 'support@maideasy.in',
    supportPhone: '1800-XXX-XXXX',
  },
  location: {
    supportedCities: SUPPORTED_CITIES,
    supportedAreas: SUPPORTED_AREAS[SUPPORTED_CITIES[0]],
    defaultRadius: 5,
  },
  maid: {
    registrationEnabled: true,
    freeRegistration: true,
    registrationFee: 0,
    approvalRequired: true,
    aadhaarRequired: true,
    selfieRequired: true,
  },
  services: SERVICE_CATEGORIES,
  pricing: {
    hourlyEnabled: true,
    dailyEnabled: true,
    monthlyEnabled: true,
    platformFeePercent: 5,
    taxPercent: 0,
    currency: 'INR',
  },
  booking: {
    cancellationWindowHours: 4,
    advanceBookingDays: 30,
    bookingExpiryMinutes: 30,
  },
  payment: {
    razorpayEnabled: true,
    phonePeEnabled: true,
  },
  maintenance: {
    maintenanceMode: false,
    appVersion: '1.0.0',
  },
};
